apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextflix
  labels:
    app: nextflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextflix
  template:
    metadata:
      labels:
        app: nextflix
    spec:
      containers:
        - name: nextflix
          image: doramar97/nextflix-int:613d90db24e97671418cd40980672e7734ce1276
          ports:
            - containerPort: 3000
