apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/doramar97/config.git
    targetRevision: main
    path: apps/sample
  destination:
    server: https://kubernetes.default.svc
    namespace: default